Maintain separate ~gcloud config configurations~ for work and
personal. Create a personal configuration and authorize it.

#+begin_src sh
gcloud config configurations list
gcloud config configurations create personal
gcloud config set account <email>
gcloud config set project <project>
gcloud auth login
#+end_src

Zone and project should be automatically set, allowing those flags to
be omitted from following commands.

#+begin_src sh
gcloud beta compute ssh <compute-instance-name>
#+end_src

** Granting permissions to Terraform
#+begin_src
gcloud iam service-accounts get-iam-policy terraform@griffith-lab.iam.gserviceaccount.com > iamPolicy.yaml
#+end_src
then modify ~iamPolicy.yaml~ to desired settings, and set it
#+begin_src
gcloud iam service-accounts set-iam-policy terraform@griffith-lab.iam.gserviceaccount.com iamPolicy.yaml
#+end_src

** Cleanup
Merge roles into a single CromwellService role:
- storage.objectCreator
- storage.objectViewer
- genomics.pipelinesRunner
- genomics.admin
- iam.serviceAccountUser
- storage.objects.create


** Running Cromwell with GCP backup

running in docker container fails with this error
```
/cromwell-executions/wf_hello/dc66016b-4821-4f8b-b8f4-ecc28cf6a5b2/call-hello/execution/script.submit: line 5: docker: command not found
cat: /cromwell-executions/wf_hello/dc66016b-4821-4f8b-b8f4-ecc28cf6a5b2/call-hello/execution/docker_cid: No such file or directory
/cromwell-executions/wf_hello/dc66016b-4821-4f8b-b8f4-ecc28cf6a5b2/call-hello/execution/script.submit: line 14: docker: command not found
cat: /cromwell-executions/wf_hello/dc66016b-4821-4f8b-b8f4-ecc28cf6a5b2/call-hello/execution/docker_cid: No such file or directory
/cromwell-executions/wf_hello/dc66016b-4821-4f8b-b8f4-ecc28cf6a5b2/call-hello/execution/script.submit: line 17: docker: command not found
```
Implying that the docker image needs... docker installed? This is
probably a problem with the configuration not being honored.
Exit rabbit hole, come back later.

** Getting files uploaded to bucket!

Still running into following problems, largest of which is rate
limiting:

[2021-03-10 10:47:08,38] [warn] This actor factory is deprecated. Please use cromwell.backend.google.pipelines.v1alpha2.PipelinesApiLifecycleActorFactory for PAPI v1 or cromwell.backend.google.pipelines.v2beta.PipelinesApiLifecycleActorFactory for PAPI v2
naive replacement here results in a ton of stack traces

[2021-03-10 10:47:08,73] [warn] 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)

[2021-03-10 10:47:09,84] [warn] The PEM file format will be deprecated
in the upcoming Cromwell version. Please use JSON instead.

#+begin_quote
[2021-03-10 10:47:42,49] [warn] PAPI request worker had 1 failures making 1 requests:
{"domain":"global",
"message":"Quota exceeded for quota metric 'v1alpha2 requests' and limit 'v1alpha2 requests per minute' of service 'genomics.googleapis.com' for consumer 'project_number:190642530876'.",
"reason":"rateLimitExceeded"}
#+end_quote
