include required(classpath("application"))
include "akka-http-version"
webservice {
  port = 8000
  interface = 0.0.0.0
  binding-timeout = 5s
  instance.name = "cromwell"
}
docker {
  hash-lookup {
    enabled = false
  }
}
 
backend {
  default = "slurm"
  providers {
    slurm {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
        # default JHU walltime looks like its 1 day. We can probably do something smarter here
        Int runtime_minutes = 1440
        Int cpu = 2
        String? docker
        Int memory_gb = 4
        """
        submit = """
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${out} \
              -e ${err} \
              -t ${runtime_minutes} \
              --mem=${memory_gb}G \
              ${"-c " + cpu} \
              --wrap "/bin/bash ${script}"
        """
        submit-docker = """
            IMG_NAME=$(echo ${docker} | tr ':/' '_')
            # Submit the script to SLURM
            sbatch \
              --wait \
              -J ${job_name} \
              -D ${cwd} \
              -o ${cwd}/execution/stdout \
              -e ${cwd}/execution/stderr \
              -t ${runtime_minutes} \
              --mem=${memory_gb}G \
              ${"-c " + cpu} \
              --wrap "TMP_HOST_DIR=/tmp/\$USER/slurm-\$SLURM_JOB_ID; mkdir -p \$TMP_HOST_DIR; singularity exec --bind ${cwd}:${docker_cwd},\$TMP_HOST_DIR:/tmp /projects/beyond_binding/cromwell_immuno_test/shared-sif-images/$IMG_NAME.sif ${job_shell} ${script}"
        """

        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"
        filesystems {
          local {
            localization = ["soft-link", "copy"]
            docker.allow-soft-links: true
          }
        }
      }
    }
  }
}

akka.http
{
  parsing
  {
    max-chunk-size = 2m
  }
}
